# Generated by Django 4.1.1 on 2022-10-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_desc_contact_descb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='descb',
            new_name='comment',
        ),
    ]
